export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED';

export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_FILES = 'UPDATE_FILES';
export const UPDATE_ROOM = 'UPDATE_ROOM';

export const CLEAR_FILES = 'CLEAR_FILES';
export const CHANGE_PATH = 'CHANGE_PATH';